export const environment = {
  production: true
};

export const firebaseConfigProd = {
  apiKey: "AIzaSyB0pu9JQZPDHbLU0cNJzPeLFB14a7Zta_k",
  authDomain: "kitelx-prod.firebaseapp.com",
  databaseURL: "https://kitelx-prod-default-rtdb.firebaseio.com",
  projectId: "kitelx-prod",
  storageBucket: "kitelx-prod.appspot.com",
  messagingSenderId: "33604323646",
  appId: "1:33604323646:web:c55282db8a5482da7d846f",
  measurementId: "G-PT8TQKTK29"
}


export const TERMOS_USO = "I – CONDIÇÕES GERAIS "+
"1.1.    O PRESENTE DOCUMENTO CONTÉM OS TERMOS E CONDIÇÕES DE USO PARA A UTILIZAÇÃO DOS CLASSIFICADOS NO PORTAL, VINCULANDO AUTOMATICAMENTE TODOS OS SEUS USUÁRIOS, CONFORME DEFINIÇÕES ABAIXO."
"1.2.    A UTILIZAÇÃO DOS CLASSIFICADOS NO PORTAL IMPLICA NA ANUÊNCIA COM OS TERMOS E CONDIÇÕES ORA ESTABELECIDOS (AS “CONDIÇÕES”)."
"1.3.    TODAS AS REGRAS APLICÁVEIS AO USO DOS CLASSIFICADOS NO PORTAL, INCLUÍDAS NESTAS CONDIÇÕES OU EM QUALQUER OUTRO DOCUMENTO RELACIONADO, SERÃO DISPONIBILIZADAS NO ENDEREÇO VIRTUAL [HTTPS://KITELX.COM.BR/CLASSIFICADOS-TERMO-DE-USO] PREVIAMENTE À SUA ENTRADA EM VIGOR."
 
"II – TERMOS DEFINIDOS"
"2.1.    SEMPRE QUE UTILIZADOS NESTAS CONDIÇÕES, OS TERMOS ABAIXO TERÃO O SEGUINTE SIGNIFICADO:"
"A) “ANUNCIANTE” SIGNIFICA TODO USUÁRIO DOS CLASSIFICADOS DO PORTAL, PESSOA FÍSICA OU JURÍDICA, QUE O UTILIZE PARA A VEICULAÇÃO DE ANÚNCIOS."
"B) “ANÚNCIO” SIGNIFICA UM PRODUTO INFORMADO POR UM ANUNCIANTE COMO PARA VENDA ATRAVÉS DOS CLASSIFICADOS DO PORTAL, DE ACORDO COM AS CONDIÇÕES."
"C) “CONDIÇÕES” TEM O SIGNIFICADO INFORMADO NA CLÁUSULA 3.1. DESTE INSTRUMENTO."
"D) “PORTAL” SIGNIFICA O SITE OU PORTAL ONLINE DISPONIBILIZADO PELO KITE LX ATRAVÉS DO QUAL ANUNCIANTES PODERÃO VEICULAR ANÚNCIOS PARA COMERCIALIZAÇÃO DE PRODUTOS NOS CLASSIFICADOS."
"E) “PRODUTOS” SIGNIFICA EQUIPAMENTOS, ACESSÓRIOS E OU PEÇAS DE KITESURF"
"F) “USUÁRIO” SIGNIFICA TODO AQUELE QUE ACESSAR O PORTAL."
 
"III  – CONDIÇÕES GERAIS DO SERVIÇO"
"3.1.    A KITE LX SE RESERVA O DIREITO DE ALTERAR, A QUALQUER TEMPO, NO TODO OU EM PARTE, AS CONDIÇÕES, OU, AINDA, DE ESTABELECER DETERMINADAS REGRAS EM SEPARADO PARA PARTES ESPECÍFICAS DO PORTAL, QUE PREVALECERÃO SOBRE AS PRESENTES CONDIÇÕES."
"3.2.    A KITE LX NÃO REALIZA QUALQUER ATIVIDADE DE INTERMEDIAÇÃO ENTRE ANUNCIANTES E DEMAIS USUÁRIOS, NÃO SENDO CONSIDERADO, EM QUALQUER HIPÓTESE, RESPONSÁVEL POR QUALQUER OBRIGAÇÃO RELACIONADA A TAIS ATIVIDADES, INCLUSIVE PERANTE TERCEIROS."
"3.3.    A KITE LX DEVERÁ SER SEMPRE CONSIDERADA, PERANTE OS USUÁRIOS, COMO TERCEIRO NÃO INTERESSADO NAS NEGOCIAÇÕES QUE VENHAM A SER REALIZADAS ATRAVÉS DOS CLASSIFICADOS DO PORTAL, NÃO ESTABELECENDO QUALQUER VÍNCULO DE ASSOCIAÇÃO, SOCIEDADE OU EMPREGO COM QUALQUER USUÁRIO DO PORTAL."
"3.4.    OS USUÁRIOS CONCORDAM E ACEITAM QUE NÃO DEVERÃO, EM QUALQUER HIPÓTESE, ATUAR, INFORMAR OU DAR A ENTENDER, ATRAVÉS DO USO DOS CLASSIFICADOS DO PORTAL OU NÃO, QUE POSSUEM QUALQUER VÍNCULO OU ACORDO EMPRESARIAL COM A KITE LX, OU, AINDA, QUE ESTEJAM ATUANDO EM NOME DA KITE LX, DIRETA OU INDIRETAMENTE."
"3.5.    AO ACESSAR OU UTILIZAR OS CLASSIFICADOS DO PORTAL, OS USUÁRIOS ESTARÃO RECONHECENDO TEREM LIDO TODAS AS PRESENTES CONDIÇÕES E A ELAS DADO SUA ANUÊNCIA."
"3.6.    CASO O ANUNCIANTE SEJA UMA PESSOA JURÍDICA, A PESSOA QUE EM SEU NOME UTILIZAR O PORTAL DECLARA E GARANTE POSSUIR SUFICIENTES PODERES PARA REPRESENTAR TAL PESSOA JURÍDICA E/OU PARA ADERIR ÀS PRESENTES CONDIÇÕES."
 
"IV – MODIFICAÇÕES NO PORTAL"
"4.1.    A KITE LX SE RESERVA AO DIREITO DE, A SEU EXCLUSIVO CRITÉRIO E CONVENIÊNCIA, DE TEMPOS EM TEMPOS EFETUAR MODIFICAÇÕES, TOTAL OU PARCIALMENTE, NOS CLASSIFICADOS DO PORTAL E NESTAS CONDIÇÕES."
"4.2.    A UTILIZAÇÃO DOS CLASSIFICADOS DO PORTAL PELOS USUÁRIOS IMPLICA NA ACEITAÇÃO DA CONFIGURAÇÃO DO PORTAL NA DATA EM QUE TAL USO TENHA OCORRIDO, AINDA QUE ENVOLVENDO ANÚNCIOS VEICULADOS NO CLASSIFICADOS DO PORTAL ANTERIORMENTE A ESSE ACESSO."
 
"V – ELEGIBILIDADE"
"5.1.    OS ANUNCIANTES QUE VEICULAREM ANÚNCIOS ATRAVÉS DOS CLASSIFICADOS DO PORTAL DEVERÃO POSSUIR PLENA CAPACIDADE LEGAL PARA CONTRATAR OS SERVIÇOS DISPONIBILIZADOS PELO PORTAL, SENDO CERTO E ACEITO QUE A UTILIZAÇÃO DOS CLASSIFICADOS DO PORTAL IMPLICA NUMA DECLARAÇÃO, PELO ANUNCIANTE, DO ATENDIMENTO A TAL REQUISITO."
"5.2.    A KITE LX PODERÁ, NA FORMA E NOS LIMITES PREVISTOS PELA LEI BRASILEIRA, MANTER UM BANCO DE DADOS COM DADOS DO USUÁRIO E DE SEU HISTÓRICO DE USO DOS CLASSIFICADOS DO PORTAL."
 
"VI – FUNCIONAMENTO DOS CLASSIFICADOS DO PORTAL"
"6.1.    ATRAVÉS DOS CLASSIFICADOS DO PORTAL, ANUNCIANTES PODERÃO VEICULAR ANÚNCIOS DE PRODUTOS, MEDIANTE SEU PRÉVIO CADASTRO NA ÁREA ESPECIALMENTE DESTINADA A TAL FINALIDADE DO PORTAL."
"6.2.    O PROPÓSITO DA KITE LX, ATRAVÉS DOS CLASSIFICADOS DO PORTAL, É OFERECER MEIOS TECNOLÓGICOS PARA QUE ANUNCIANTES POSSAM NEGOCIAR DIRETAMENTE OS PRODUTOS COM OS DEMAIS USUÁRIOS."
"6.3.    A KITE LX NÃO SERÁ CONSIDERADA EM QUALQUER HIPÓTESE COMO PROPRIETÁRIO DOS PRODUTOS, TAMPOUCO FORNECEDOR OU INTERMEDIÁRIO NO FORNECIMENTO DOS PRODUTOS, SENDO RESPONSÁVEL APENAS PELO FUNCIONAMENTO DOS CLASSIFICADOS DO PORTAL."
"6.4.    A KIITE LX NÃO SERÁ RESPONSABILIZADA EM QUALQUER HIPÓTESE PELA VERACIDADE DAS INFORMAÇÕES CONTIDAS EM QUALQUER ANÚNCIO, QUE DEVERÃO SER CONFIRMADAS PELO USUÁRIO JUNTO AO ANUNCIANTE."
"6.5.    A KITE LX ENVIDARÁ SEUS MELHORES ESFORÇOS VISANDO A MANUTENÇÃO DOS CLASSIFICADOS DO PORTAL EM FUNCIONAMENTO 24 (VINTE E QUATRO) HORAS POR DIA, DURANTE TODOS OS DIAS DA SEMANA, NÃO SE RESPONSABILIZANDO, ENTRETANTO, POR EVENTUAIS INDISPONIBILIDADES DE ACESSO DECORRENTES DE PROBLEMAS TÉCNICOS."
 
"VII – REGISTRO NOS CLASSIFICADOS DO PORTAL"
"7.1.    A CRIAÇÃO DE CONTAS POR ANUNCIANTES NOS CLASSIFICADOS DO PORTAL PODERÁ SE DAR MEDIANTE O PREENCHIMENTO DA FICHA DE CADASTRO PARA TAL FINALIDADE DISPONÍVEL NO ENDEREÇO ELETRÔNICO DO PORTAL, OU, AINDA, ATRAVÉS DA UTILIZAÇÃO DA SUA CONTA EM REDES SOCIAIS DE TERCEIROS, QUANDO PERMITIDO PELO PORTAL."
"7.2.    A VINCULAÇÃO DA CONTA A UMA CONTA EM REDES SOCIAIS DE TERCEIROS PODERÁ SE DAR (A) ATRAVÉS DO FORNECIMENTO DE SUAS INFORMAÇÕES DE ACESSO A TAIS CONTAS PARA O PORTAL; OU (B) PELA CONCESSÃO DE PERMISSÃO PARA QUE O PORTAL ACESSE A CONTA DE PROPRIEDADE DO ANUNCIANTE NA REDE SOCIAL DE TERCEIROS."
"7.3.    O ANUNCIANTE RECONHECE E ACEITA SER RESPONSÁVEL PERANTE A REDE SOCIAL DE TERCEIRO PELAS INFORMAÇÕES FORNECIDAS AO PORTAL E/OU POR ELE ACESSADAS DE QUALQUER FORMA, OUTORGANDO AO PORTAL PLENA AUTORIZAÇÃO PARA UTILIZAÇÃO DAS INFORMAÇÕES NECESSÁRIAS PARA CONCLUSÃO DA CRIAÇÃO DA SUA CONTA."
"7.4.    EM HIPÓTESE ALGUMA A KITE LX SERÁ RESPONSÁVEL OU DE QUALQUER MANEIRA ATUARÁ COMO INTERMEDIÁRIO NO RELACIONAMENTO EXISTENTE ENTRE ANUNCIANTES E A REDE SOCIAL DE TERCEIRO, PERMANECENDO ALHEIO A TAL VÍNCULO JURÍDICO."
"7.5.    A KITE LX SE RESERVA O DIREITO DE CANCELAR A CONTA DO ANUNCIANTE QUE CONTENHA INFORMAÇÕES DIFERENTES, IMPRECISAS, INCORRETAS OU FRAUDULENTAS, OU, AINDA, DE QUALQUER MANEIRA EM DESACORDO COM AS PRESENTES CONDIÇÕES."
"7.6.    O ANUNCIANTE NÃO PODERÁ COMPARTILHAR SUA CONTA COM TERCEIROS TAMPOUCO FRANQUEAR-LHES ACESSO À MESMA, EXCETO COM EXPRESSA AUTORIZAÇÃO DA KITE LX."
 
"VIII – ANÚNCIOS"
"8.1.    OS ANUNCIANTES PODERÃO POSTAR NOS CLASSIFICADOS DO PORTAL ANÚNCIOS RELACIONADOS A PRODUTOS DISPONIBILIZADOS, COM TODAS AS INFORMAÇÕES QUE O PORTAL VENHA A SOLICITAR DE FORMA A IDENTIFICAR PERFEITAMENTE AS CARACTERÍSTICAS E A DISPONIBILIDADE DESSES PRODUTOS, RESPONDENDO EXCLUSIVAMENTE PELA FIDELIDADE E ACUIDADE DAS INFORMAÇÕES VEICULADAS."
"8.2.    OS ANUNCIANTES DEVERÃO DECLARAR, POR OCASIÃO DA PUBLICAÇÃO DO ANÚNCIO E EM CAMPO ESPECÍFICO DISPONIBILIZADO PARA ESSA FINALIDADE NOS CLASSIFICADOS DO PORTAL, QUE SÃO OS LEGÍTIMOS PROPRIETÁRIOS DOS PRODUTOS ANUNCIADOS, QUE ESTES SE ENCONTRAM DESEMBARAÇADOS E/OU LIVRES DE QUAISQUER ÔNUS, BEM COMO QUE POSSUEM TODOS OS DOCUMENTOS FISCAIS HÁBEIS A COMPROVAR A LEGÍTIMA AQUISIÇÃO DESSES BENS, ESPECIFICANDO QUAL TIPO DE DOCUMENTO FISCAL POSSUEM."
"8.3.    OS DEMAIS USUÁRIOS PODERÃO TER ACESSO AOS ANÚNCIOS MEDIANTE ACESSO AO PORTAL, SENDO CERTO E ACEITO QUE OS RESULTADOS DE BUSCA POR ANÚNCIOS PODERÃO DEPENDER DE FATORES VARIADOS, INCLUSIVE, DE SERVIÇOS QUE POSSAM VIR A SER CONTRATADOS PELO ANUNCIANTE JUNTO AO PORTAL PARA MAIOR DESTAQUE DO ANÚNCIO."
"8.4.    OS ANUNCIANTES NÃO PODERÃO, EM QUALQUER HIPÓTESE, ANUNCIAR OS MESMOS PRODUTOS EM OUTROS VEÍCULOS E/OU PORTAIS, PRÓPRIOS OU NÃO, POR VALORES INFERIORES AOS OFERECIDOS ATRAVÉS DOS ANÚNCIOS, SENDO DESDE JÁ CERTO E ACEITO QUE O DESCUMPRIMENTO DESTA OBRIGAÇÃO IMPLICARÁ NA EXCLUSÃO IMEDIATA DO ANÚNCIO E/OU DO ANUNCIANTE DO PORTAL A EXCLUSIVO CRITÉRIO DO TRILO."
"8.5.    ANÚNCIOS POSTADOS SERÃO AUTOMATICAMENTE CONSIDERADOS INATIVOS E RETIRADOS DOS RESULTADOS DE BUSCA DOS CLASSIFICADOS DO PORTAL APÓS 60 (SESSENTA) DIAS DA SUA PUBLICAÇÃO, PODENDO SER REATIVADOS PELO ANUNCIANTE ATRAVÉS DO PORTAL EM CAMPO ESPECÍFICO COM ESSA FINALIDADE."
"8.6.    ANÚNCIOS INATIVOS HÁ MAIS DE 6 (SEIS) MESES PODERÃO SER DEFINITIVAMENTE EXCLUÍDOS DOS BANCOS DE DADOS DOS CLASSIFICADOS DO PORTAL, A EXCLUSIVO CRITÉRIO DO TRILO, NÃO SENDO ESTE RESPONSÁVEL PELA MANUTENÇÃO DE QUAISQUER INFORMAÇÕES SOBRE TAIS ANÚNCIOS APÓS A SUA EXCLUSÃO."
 
"IX – NENHUM ENDOSSO"
"9.1.    A KITE LX NÃO SE COMPROMETE QUANTO À VERACIDADE DAS INFORMAÇÕES REPASSADAS PELOS USUÁRIOS ATRAVÉS DO PORTAL, A QUAIS PERMANECERÃO COMO DE RESPONSABILIDADE DE QUEM AS FORNECEU."
 
"X – NEGOCIAÇÃO E COBRANÇA"
"10.1.    ANUNCIANTES E OS DEMAIS USUÁRIOS PODERÃO NEGOCIAR LIVREMENTE OS PRODUTOS, DIRETAMENTE E SEM A INTERMEDIAÇÃO DO PORTAL, ATRAVÉS DOS DADOS CADASTRAIS E/OU DE CONTATO FORNECIDOS."
"10.2.    A PUBLICAÇÃO DE ANÚNCIOS NOS CLASSIFICADOS DO PORTAL É GRATUITA, PODENDO A KITE LX, A SEU EXCLUSIVO CRITÉRIO, OFERECER AOS ANUNCIANTES SERVIÇOS ADICIONAIS PAGOS QUE PERMITAM MAIOR DESTAQUE AO ANÚNCIO NO CLASSIFICADOS DO PORTAL, ENTRE OUTROS."
"10.3.    O ANÚNCIO DEVERÁ CONTER TODAS AS INFORMAÇÕES SOLICITADAS PELO PORTAL COMO NECESSÁRIAS PARA A SUA VEICULAÇÃO, AS QUAIS PODEM MUDAR DE TEMPOS EM TEMPOS, CONFORME CRITÉRIO DO PORTAL."
 
"XI – OBRIGAÇÕES FINANCEIRAS DOS ANUNCIANTES"
"11.1.    O ANUNCIANTE FICARÁ RESPONSÁVEL PELO PAGAMENTO A KITE LX PELOS SERVIÇOS ADICIONAIS PASSÍVEIS DE COBRANÇA QUE VENHA A ADQUIRIR DO PORTAL."
 
"XII – RESPONSABILIDADES DOS USUÁRIOS"
"12.1.    OS USUÁRIOS DO PORTAL SE COMPROMETEM A:"
"A) NÃO UTILIZAR O PORTAL COM QUALQUER PROPÓSITO CRIMINOSO, NOCIVO, ILEGAL, AMEAÇADOR, OFENSIVO, CALUNIOSO, DIFAMATÓRIO, DESRESPEITOSO, INFUNDADO, DISCRIMINATÓRIO E/OU QUE DEIXE DE ATENDER CRITÉRIOS DE VERACIDADE;"
"B) NÃO ENVIAR OU TRANSMITIR QUAISQUER TIPOS DE INFORMAÇÕES QUE INDUZAM, INCITEM OU RESULTEM EM ATITUDES DISCRIMINATÓRIAS, MENSAGENS VIOLENTAS OU DELITUOSAS QUE ATENTEM CONTRA A MORAL E BONS COSTUMES E QUE CONTRARIEM A ORDEM PÚBLICA; QUE ASSEDIEM OU INVADAM A PRIVACIDADE ALHEIA, SEJAM VULGARES, PROFANAS, SEXUALMENTE EXPLÍCITAS, OBSCENAS, RACIAL OU ETNICAMENTE OFENSIVAS, OU, DE QUALQUER OUTRA FORMA, INACEITÁVEL POR CAUSAR RISCOS OU DANOS DE IMAGEM, MATERIAIS OU MORAIS A KITE LX, SEUS EMPREGADOS, QUALQUER UM DOS SEUS COLABORADORES OU TERCEIROS;"
"C) NÃO SE CADASTRAR COM INFORMAÇÕES FALSAS OU DE PROPRIEDADE DE TERCEIROS;"
"D) NÃO ENVIAR QUALQUER INFORMAÇÃO QUE NÃO SEJA DE DOMÍNIO PÚBLICO SOBRE A KITE LX OU QUALQUER OUTRA EMPRESA OU PESSOA, SEM A DEVIDA AUTORIZAÇÃO. ISSO INCLUI FORNECER INFORMAÇÕES (E-MAIL, ENDEREÇO, TELEFONE E OUTRAS) DE NATUREZA NITIDAMENTE PESSOAL DO PRÓPRIO USUÁRIO OU DE TERCEIROS;"
"E) NÃO APROVEITAR O MESMO ANÚNCIO CONTRATADO PARA INSERIR INFORMAÇÕES E/ OU FOTOS, OU, DE QUALQUER MODO, FAZER REFERÊNCIA A OUTRO(S) PRODUTO(S);"
"F) NÃO ALTERAR, APAGAR OU CORROMPER DADOS E INFORMAÇÕES DE TERCEIROS;"
"G) NÃO VIOLAR A PRIVACIDADE DE OUTROS INTERNAUTAS OU USUÁRIOS;"
"H) NÃO ENVIAR OU TRANSMITIR ARQUIVOS COM VÍRUS DE COMPUTADOR, COM CONTEÚDO DESTRUTIVO, INVASIVO OU QUE CAUSEM DANO PERMANENTE OU TEMPORÁRIO NOS EQUIPAMENTOS DO DESTINATÁRIO, DA KITE LX OU NO PORTAL;"
"I) NÃO UTILIZAR ENDEREÇOS DE COMPUTADORES, DE REDE OU DE CORREIO ELETRÔNICO FALSOS;"
"J) NÃO INFRINGIR QUALQUER DIREITO A PATENTE, MARCA, SEGREDO INDUSTRIAL, COPYRIGHT, OUTROS DIREITOS DE PROPRIEDADE DE QUALQUER PARTE, OU CONFIGURAR QUALQUER TIPO DE ATOS OU OMISSÕES CONTRÁRIOS À LEGISLAÇÃO E/OU CONSIDERADOS CRIMES, INCLUINDO, MAS NÃO SE LIMITANDO, A CRIMES CONTRA A HONRA (INJÚRIA, DIFAMAÇÃO, CALÚNIA), CRIMES DE CONCORRÊNCIA DESLEAL E OUTROS CRIMES TIPIFICADOS NA LEI DE PROPRIEDADE INDUSTRIAL (9.279/96) E NA LEI DE DIREITO AUTORAL (9.610/98);"
"K) NÃO UTILIZAR OS DADOS PARA CONTATO DE OUTROS USUÁRIOS COM OUTRO PROPÓSITO QUE NÃO SEJA O DE ENCAMINHAR PROPOSTA COMERCIAL VINCULADA AO ANÚNCIO;"
"L) NÃO UTILIZAR OS PRODUTOS E/OU SERVIÇOS DISPONÍVEIS NO PORTAL PARA FINS DIVERSOS DAQUELES A QUE SE DESTINAM;"
"M) NÃO UTILIZAR O PORTAL PARA FINS OUTROS ALÉM DAQUELES QUE ORDINARIAMENTE SE ESPERA DE UM INTERNAUTA E/OU USUÁRIO INTERESSADO NA KITE LX."
 
"XIII – OBRIGAÇÕES DOS USUÁRIOS E POLÍTICA DE PRIVACIDADE"
"13.1.    OS USUÁRIOS, INDEPENDENTEMENTE DE QUALQUER FORMALIZAÇÃO, DEVERÃO UTILIZAR O PORTAL DE ACORDO COM OS TERMOS E CONDIÇÕES ORA ESTABELECIDOS,  DEVENDO SE ABSTER DA PRÁTICA DE QUAISQUER ATOS CAPAZES DE DISTORCER OS PROPÓSITOS E USOS INFORMADOS NESTAS CONDIÇÕES PARA O PORTAL, EM ESPECIAL: (A) A UTILIZAÇÃO DO PORTAL PARA A PRÁTICA DE ATOS ILÍCITOS OU CRIMINOSOS; (B) A UTILIZAÇÃO DE SUBTERFÚGIOS PARA OBTENÇÃO DE INFORMAÇÕES SIGILOSAS DETIDAS PELA KITE LX; OU (C) A UTILIZAÇÃO DE ROBÔS OU OUTROS MEIOS PARA UTILIZAÇÃO E/OU CONTROLE SIMULTÂNEO DE MAIS DE UMA CONTA."
"13.2.    TODAS AS INFORMAÇÕES QUE VENHAM A SER FORNECIDAS PELOS USUÁRIOS ATRAVÉS DO PORTAL, INCLUSIVE LOGS E/OU DADOS DE ACESSO, SÃO DE PROPRIEDADE DA KITE LX, SENDO INCORPORADAS AO SEU BANCO DE DADOS."
"13.3.    OS ANUNCIANTES DEVERÃO FORNECER E MANTER EM TAL CONDIÇÃO DADOS VERDADEIROS, PRECISOS, ATUAIS E COMPLETOS."
"13.4.    AS INFORMAÇÕES CONTIDAS NOS BANCOS DE DADOS DA KITE LX SERÃO TRATADAS DE FORMA SEGURA E PROTEGIDAS CONTRA A UTILIZAÇÃO POR TERCEIROS."
"13.5.    EXCETO SE DE OUTRO MODO SOLICITADO POR ÓRGÃO OU ENTIDADE GOVERNAMENTAL COM PODER DE POLÍCIA OU JURISDICIONAL, NENHUMA DAS INFORMAÇÕES FORNECIDAS PELOS USUÁRIOS A KITE LX SERÃO FORNECIDAS A TERCEIROS SEM O SEU EXPRESSO CONSENTIMENTO PRÉVIO."
 
"XIV – RESCISÃO E LIMITAÇÃO DE RESPONSABILIDADE"
"14.1.    OS ANUNCIANTES PODERÃO RESCINDIR SUA RELAÇÃO CONTRATUAL COM A KITE LX MEDIANTE A SOLICITAÇÃO VIA E-MAIL, DESDE QUE NÃO TENHA QUAISQUER PENDÊNCIAS OU OBRIGAÇÕES FINANCEIRAS EM ABERTO."
"14.2.    A KITE LX PODERÁ RESCINDIR SUA RELAÇÃO CONTRATUAL COM OS ANUNCIANTES A QUALQUER TEMPO, MEDIANTE SUA EXCLUSÃO DO PORTAL, EM CASO DE DESCUMPRIMENTO DAS PRESENTES CONDIÇÕES."
"14.3.    OS USUÁRIOS DEVERÃO PROTEGER E MANTER INDENE A KITE LX EM QUAISQUER DEMANDAS ORIGINAIS E/OU POR QUALQUER RAZÃO RELACIONADAS COM O USO DO PORTAL INDEVIDO, INCORRETO OU CONTRÁRIO À LEI, ARCANDO COM TODOS OS CUSTOS RELACIONADOS COM A DEFESA E REPARAÇÃO DE DANOS EVENTUALMENTE SOFRIDOS PELA KITE LX POR TAL RAZÃO."
"14.4.    A KITE LX NÃO É RESPONSÁVEL PELA VERACIDADE DAS INFORMAÇÕES REPASSADAS PELOS ANUNCIANTES ATRAVÉS DO PORTAL, CUJA VERIFICAÇÃO DE VERACIDADE É DE RESPONSABILIDADE EXCLUSIVA DESTES."
 
"XV – JURIDIÇÃO E FORO DE ELEIÇÃO"
"15.1.    AS PRESENTES CONDIÇÕES SERÃO INTERPRETADAS DE ACORDO COM AS LEIS DO BRASIL."
"15.2.    QUALQUER CONFLITO ORIUNDO OU RELACIONADO ÀS PRESENTES CONDIÇÕES SERÁ OBJETO DE APRECIAÇÃO PELO FORO COMPETENTE DA CIDADE DO RIO DE JANEIRO/RJ."