name: Workflow Homologacao 

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.0.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.0.1

    - name: Verify Python version
      run: python --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover
        
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install -f

      - name: Run ESLint
        run: npm test

      - name: Run tests
        run: npm test

      - name: Check code coverage
        run: npm run coverage

      - name: Build application
        run: npm run build 
